# Project information
site_name: '惜余'
site_author: 'MarkoXu'
site_url: 'https://www.markoxu.com/'
site_description: '当一个有趣的人儿~'

# Repository
edit_uri: ''
docs_dir: docs/content/
site_dir: 'www.markoxu.com'

# Copyright
copyright: 'Copyright &copy; 2021 MarkoXu'

# Extra CSS
extra_css:
  - assets/css/extra.css

# Extra JS
extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: zh
  palette:
    # Light mode
    - purple: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font: false
  icon:
    repo: fontawesome/brands/github
    logo: logo
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:

      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/markoxu
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/solid/paper-plane
      link: https://gitter.im/markoxu/blog
    - icon: fontawesome/solid/envelope
      link: mailto:704712641@qq.com

# Page tree
nav:
  - 首页: index.md
  - 文章列表:
    - 文章索引: docs/overview.md
    - 剑指Offer:
      - 题目汇总: docs/code-interviews-offer/overview.md
      - 第1章: docs/code-interviews-offer/chapter-first.md
      - 第2章: docs/code-interviews-offer/chapter-second.md
      - 第3章: docs/code-interviews-offer/chapter-third.md
      - 第4章: docs/code-interviews-offer/chapter-forth.md
      - 第5章: docs/code-interviews-offer/chapter-fifth.md
      - 第6章: docs/code-interviews-offer/chapter-sixth.md
      - 第7章: docs/code-interviews-offer/chapter-seventh.md
    - LeetCode:
      - 题目汇总: docs/leetcode/overview.md
    - 行情中心:
        - 行情汇总: docs/market-center/overview.md
        - 涨跌统计: docs/market-center/zdtj.md
        - 大盘云图: docs/market-center/dpyt.md
        - 指数估值: docs/market-center/zsgz.md
  - 友情链接: docs/friends-link/friends-link.md
  - 关于博主: docs/about-me/about-me.md
